### ISSUE TITLE
Gnome on Kali linux doesnt work

### ISSUE THREAD

**Issue by THEBIGTOMMY13DEV** [sabamdarif/modded-kali#4]
vnc is not working when I install the gui.sh in gnome gui

**Comment by sabamdarif** [comment]
Just go to root/.vnc
then nano xstartup
then there is a line echo "gnome-shell --x11
just remove the word  echo "  and leave  only gnome-shell --x11 then save it

it a syntax error it will be fix soon

**Comment by sabamdarif** [comment]
This problem is now fixed, you can use the latest script to install it 

see this for more details :-  https://github.com/sabamdarif/modded-kali/commit/8eb0e59910536301ff51fad251e07ef6659ec0a4
