### ISSUE TITLE
It always doesn't work when I try to run the code that is given it doesn't make the vncserver start

### ISSUE THREAD

**Issue by THEBIGTOMMY13DEV** [sabamdarif/modded-kali#5]
Hi I have an issue of the vncserver not starting and please always run your scripts to know if the script works 100% of the time because your a developer @sabamdarif

**Comment by sabamdarif** [comment]
i will test it

**Comment by sabamdarif** [comment]
> Hi I have an issue of the vncserver not starting and please always run your scripts to know if the script works 100% of the time because your a developer @sabamdarif

which desktop enviorment

**Comment by THEBIGTOMMY13DEV** [comment]
> > Hi I have an issue of the vncserver not starting and please always run your scripts to know if the script works 100% of the time because your a developer @sabamdarif
> 
> which desktop enviorment

Gnome

**Comment by THEBIGTOMMY13DEV** [comment]
Sorry for the late response

**Comment by THEBIGTOMMY13DEV** [comment]
> i will test it 

> Sounds good

**Comment by THEBIGTOMMY13DEV** [comment]
Did you test it

**Comment by sabamdarif** [comment]
> Did you test it

![Screenshot_20240530-223524_Termux](https://github.com/sabamdarif/modded-kali/assets/111168803/0e8fcf28-2bea-483c-bd05-2e1cbe75ac67)

i tried but whenever i install something it stop here , and i can not skip or bypass it , it just stuck here

**Comment by THEBIGTOMMY13DEV** [comment]
I know what I did to bypass it

**Comment by THEBIGTOMMY13DEV** [comment]
Wanna go on discord

**Comment by THEBIGTOMMY13DEV** [comment]
Btw what is that font?

**Comment by THEBIGTOMMY13DEV** [comment]
I like it

**Comment by sabamdarif** [comment]
> Btw what is that font?

SonySketch

**Comment by sabamdarif** [comment]
> Wanna go on discord

yes send the link

**Comment by THEBIGTOMMY13DEV** [comment]
> > Wanna go on discord
> 
> yes send the link

>THEBIGTOMMY13

**Comment by THEBIGTOMMY13DEV** [comment]
My username is THEBIGTOMMY13 on discord

**Comment by THEBIGTOMMY13DEV** [comment]
Which platform do you respond on better discord or Whatsapp or Snapchat or phone number

**Comment by sabamdarif** [comment]
> Which platform do you respond on better discord or Whatsapp or Snapchat or phone number

Telegram

**Comment by THEBIGTOMMY13DEV** [comment]
What is your telegram

**Comment by sabamdarif** [comment]
> What is your telegram

t.me/saba_mdarif

**Comment by THEBIGTOMMY13DEV** [comment]
Hope you respond and talk to me

**Comment by sabamdarif** [comment]
Login into Kali
Go to $HOME/.vnc
nano xstartup
Pest this 👇
export XDG_CURRENT_DESKTOP="GNOME"
sudo service dbus start
gnome-shell --x11

Save and exit
Type chmod +x xstartup
