### ISSUE TITLE
Error proot distro should be execute under proot

### ISSUE THREAD

**Issue by Indopeople1** [sabamdarif/modded-kali#6]
When I try run Kali Linux on application termux x11 in termux and the termux error show written proot distro should be executed under proot I don't know what happen

**Comment by sabamdarif** [comment]
> When I try run Kali Linux on application termux x11 in termux and the termux error show written proot distro should be executed under proot I don't know what happen

can you send a screenshot of it ?

**Comment by Indopeople1** [comment]
Okey

**Comment by Indopeople1** [comment]
![Screenshot_2024-06-17-05-46-11-42_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/sabamdarif/modded-kali/assets/172958979/eae8ea3d-1d5d-47f6-93e6-1ce56574b0af)

Here can you help it

**Comment by sabamdarif** [comment]
Run this command in termux shell not in Kali Linux

**Comment by Indopeople1** [comment]
![Screenshot_2024-06-17-05-46-11-42_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/sabamdarif/modded-kali/assets/172958979/eae8ea3d-1d5d-47f6-93e6-1ce56574b0af)

Here can you help it
